 - name: test gather facts
   hosts: node1
   #ne pas afficher les gather facts
   #gather_facts = no
   tasks:
   - name: setup
     setup:
       filter: ansible_user*
     register: __host_facts
   - name: debug
     debug:
       var: __host_facts
     # affiche toute les informations
     #debug:
     #  var: ansible_facts
