- name: installation node exporter
  hosts: node_exporter
  become: yes
  roles: 
  - node_exporter

- name: installation de prometheus/grafana
  hosts: prometheus
  become: yes
  roles:
  - prometheus
