- name: fetch
  hosts: all
  become: yes
  tasks: 
  - name: utilisation fetch
    fetch:
      src: /etc/hosts
      dest: tmp/hosts_{{ ansible_hostname }}.txt
      flat: yes
      #dest: tmp/
    # penser à créer le dossier tmp

