- name: installation local
  hosts: localhost
  connection: local
  become: yes
  tasks:
  - name: installation de nginx
    apt:
      name: nginx
      state: present
  - name: clean
    file:
      path: "{{ item }}"
      state: absent
    with_fileglob:
      - "/var/www/html/*.html"
  - name: permission
    file:
      path: "/var/www/html/*.html"
      owner: root
      recurse: yes
      state: directory
- name: fetch
  hosts: all
  become: yes
  tasks:
  - name: utilisation fetch
    fetch:
      src: /etc/hosts
      dest: /var/www/html/hosts__{{ ansible_hostname }}.txt
      flat: yes
